### ISSUE TITLE
Изменить страницу подачи обращения.

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/dniprorada#10]
После выбора услуги необходимо авторизоваться через BankID.  После авторизации переходим на форму заявки.

В заголовке страницы должно быть  название услуги.

Под заголовком: Довідка та ЧаВо про послугу (ссылка ведет на документ Google Doc, в котором описан бизнес-процесс и приведены ЧаВо)

Поля с информацией по клиенту должны быть неактвными и предзаполнены ( ФИО, телефон клиента, адрес - получаемпо bankID).

**Comment by bvv4ik** [comment]
ждем, как заработает полноценно авторизация, вроде седня обещали продеплоить...
тогда смог-бы этим куском заняться (иначе проверять не получилось-бы)

**Comment by bvv4ik** [comment]
добавил ссылку на док ЧаВо, но сам он  пустой пока...
обязательность авторизации перед заполнением формы - временно выключена, т.к. поломана БанкИД валидация... как заработает - включу
