### ISSUE TITLE
Украинская локализация активити.

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/dniprorada#12]
Перевести все интерфейсы на украинский язык.

**Comment by PavelKorchagin** [comment]
коммент

**Comment by stashuk** [comment]
Можу взятися, але давайте опишемо в слаку чи тут, що саме треба.

**Comment by kurbpa** [comment]
Необходимо:
На интерфейсах и формах активити (https://wf.dniprorada.egov.dp.ua:8080/wf-dniprorada/) перевести на укр.язык  все тексты (ссылки, кнопки, разделы, подсказки)

**Comment by stashuk** [comment]
Ок, можна на мене ставити, відпишу, як зроблю

**Comment by admiral-diver** [comment]
Тут список констант, которые нужно локализировать (org.activiti.explorer.Messages). Я уже начал немного прорабатывать эту задачу. Если хочешь, можешь скооперироваться. Быстрее будет.

**Comment by stashuk** [comment]
Чудово, можна скооперуватися. Скидай сюди чи коміть, що готове, я дороблю.

2015-03-30 11:43 GMT+01:00 Vjacheslav <notifications@github.com>:

**Comment by admiral-diver** [comment]
Ок. Если что. Skype: DN120187VVA, Email: admiral.diver@gmail.com

**Comment by PavelKorchagin** [comment]
просто супер, спасибо. задача у нас будет состоять из двух этапов 
1 - это украинизация самого активити (пункты меню, страницы etc) 2. - это формы бизнес-процессов. (они отдельно )
сейчас 1 этап

**Comment by admiral-diver** [comment]
У пользователя моей группы нет прав на push в теку test. Кто может помочь?

**Comment by admiral-diver** [comment]
Не могу слить украинскую локализацию для проекта

**Comment by dubilet** [comment]
Павел Игнатьевич, прошу помочь


--------------------------------------------
Дмитрий Дубилет
Заместитель Председателя Правления ПриватБанка,
Руководитель Направления Информационных технологий
(aka IT-директор)
Для планирования встреч: Мой Календарь
<https://www.google.com/calendar/b/0/embed?src=d.dubilet@privatbank.ua&mode=week&hl=en&ctz=Europe/Kiev&gsessionid=R-ybOEki97A1QdH82qfMyw>
Email: d.dubilet@privatbank.ua
Тел: +38 067 566 84 86
Skype: d.dubilet@gmail.com
И даже панорамный снимок моего кабинета <http://spincam.net/s/qdrv>

2015-04-01 14:10 GMT+03:00 Viacheslav Velikotskiy <notifications@github.com>
:

**Comment by admiral-diver** [comment]
Вопрос решон. Приожение переведено на украинский. Залито на тестовую. 
По возможности предлагаю пересмотреть кому-то визуальный интерфейс для дальнейшего улучшения перевода, если такой будет необходим. При необходимости могу приступить к выполнению второй части задачи.

**Comment by dubilet** [comment]
большое спасибо!


--------------------------------------------
Дмитрий Дубилет
Заместитель Председателя Правления ПриватБанка,
Руководитель Направления Информационных технологий
(aka IT-директор)
Для планирования встреч: Мой Календарь
<https://www.google.com/calendar/b/0/embed?src=d.dubilet@privatbank.ua&mode=week&hl=en&ctz=Europe/Kiev&gsessionid=R-ybOEki97A1QdH82qfMyw>
Email: d.dubilet@privatbank.ua
Тел: +38 067 566 84 86
Skype: d.dubilet@gmail.com
И даже панорамный снимок моего кабинета <http://spincam.net/s/qdrv>

1 апреля 2015 г., 15:01 пользователь Viacheslav Velikotskiy <
notifications@github.com> написал:

**Comment by kurbpa** [comment]
Спасибо!
Проверяю  локализацию.

**Comment by kurbpa** [comment]
![2](https://cloud.githubusercontent.com/assets/11442397/6941401/5c34760c-d888-11e4-8f39-8602c1026f6d.JPG)
![3](https://cloud.githubusercontent.com/assets/11442397/6941402/5f516e94-d888-11e4-83f7-8dd11f25e9e5.JPG)
![4](https://cloud.githubusercontent.com/assets/11442397/6941410/753cce7e-d888-11e4-82bc-0575c565483f.JPG)

**Comment by admiral-diver** [comment]
Да. Есть некоторые элементы, которые к сожалению перевести не удасться ввиду того, что они не локализированы разработчиками Activiti. На такие элементы я пишу им задачи на доработку. Вот пример: https://github.com/Activiti/Activiti/issues/561

Сейчас проанализирую этот участок и тоже напишу на них задачку. Спасибо!

**Comment by admiral-diver** [comment]
Отредактировано согласно выставленным коментариям в документе: https://docs.google.com/document/d/1eW5Xd6B93z518-z8AzVXwm5SgTSkfItHfrY1qk6pRt4/edit?pli=1
