### ISSUE TITLE
BankID изменение в запросе по данным - маленькое

### ISSUE THREAD

**Issue by PavelKorchagin** [e-government-ua/dniprorada#15]
Добрый, Паша есть изменение в запросе по данным - маленькое
[9:52:16] Сергей Жук: в него нужно добавить client_id
вот пример

https://bankid.privatbank.ua/DataAccessService/checked/fio?access_token=095be9eb-01e7-4045-b60b-9d71581fb4d9&client_id=d9c8b4d6-6a18-4492-a50a-2b3b4ea6285b
[9:52:55] Сергей Жук: в итоге пока 2 параметра access_token  и  client_id

**Comment by maxtmn** [comment]
а есть описание протокола сервиса?

**Comment by maxtmn** [comment]
при успешном ответе сервиса - всё ок.
при ошибке токена - сейчас имеем ответ в отличном формате. 
нужна доработка от сервиса авторизации, после чего докрутка в процессе
