### ISSUE TITLE
Activiti - настроить авторизацию по rest-у 

### ISSUE THREAD

**Issue by PavelKorchagin** [e-government-ua/dniprorada#20]
Сейчас по умолчанию она отключена.

**Comment by admiral-diver** [comment]
При доступе к методам ActivitiRestApiController организовать Basic авторизацию?

**Comment by PavelKorchagin** [comment]
сейчас можно https://52.17.126.64:8080/wf-dniprorada/service/repository/process-definitions
по ресту полностью везде ходить
предлагаю начать с Basic  авторизации так как у нас https поднят, а там посмотрим
напрямую по ресту никого не пускаем, это взаимодействие portal - activiti

**Comment by admiral-diver** [comment]
Ок. Тогда кидайте на меня. Я постараюсь за завтра сегодня-завтра сделать. Модуль авторизации можно взять тот, что используется для авториазции пользователей Activiti?

**Comment by bvv4ik** [comment]
я готов присоединиться к Вячеславу, т.к. участок очень важный и не простой
и в т.ч.. для того чтоб предварительно смоделировать целостную систему авторизации... чтоб потом не переделывать(есть значительный опыт, да и вместе веселей)

**Comment by admiral-diver** [comment]
Ок. Детали обсудим в Skype

**Comment by PavelKorchagin** [comment]
Всем добрый вечер, ребята, как у нас тут, движется?

**Comment by admiral-diver** [comment]
Добрый день. Если задача срочная, то быстро могу только подключить  Basic авторизацию (сегодня, через конфигурирование Spring-Security). Работа с токенами и bankID, до конца недели (с учетом кеширования в памяти, на удаленном источнике и закладывании механизма работы с ролями).

**Comment by PavelKorchagin** [comment]
Привет, Слава. Я думаю Basic для rest будет достаточно. Интеграцию с банкид. будет делать портал на данном этапе, нам нужно просто забанить доступ на рест и переключить портал на кастомный endpoint, basic-а с головой

**Comment by admiral-diver** [comment]
Ок. Сегодня вечером солью в тест. А более расширенные наработки выделю в отдельную задачу и перенесу в отдельную ветку.

**Comment by admiral-diver** [comment]
Реализовано и слито на тестовую платформу. Логин и пароль можно посмотреть в исходниках кода по этой ссылке: https://raw.githubusercontent.com/e-government-ua/dniprorada/test/wf-dniprorada/src/main/resources/activiti-login-context.xml
Задача на реализацию через BankID перенесена сюда: https://github.com/e-government-ua/dniprorada/issues/37

**Comment by bvv4ik** [comment]
по ходу пропал список процессов:
https://52.17.126.64/

похоже, что это с авторизацией связано..
но при этом, что странно, продолжает быть доступным кому угодно: https://52.17.126.64:8080/wf-dniprorada/service/repository/process-definitions

**Comment by admiral-diver** [comment]
Блокируются только вызовы /service/rest
Необходимо отключить авторизацию? Или вы пропишите user и pass?
Какие еще контексты необходимо включить в блокировку через Basic  авторизацию?

**Comment by admiral-diver** [comment]
Сейчас доступ закрыт на все вызовы по контексту /service
Работу отдельных интерфейсов контроллера пересмотрю
