### ISSUE TITLE
Вынести портал nodejs в отдельный репозиторий

### ISSUE THREAD

**Issue by PavelKorchagin** [e-government-ua/dniprorada#42]

**Comment by bvv4ik** [comment]
У меня один вопрос - зачем? В чем профит?
Посмотрите сколько репозиториев, у того-же Activiti: https://github.com/Activiti
(все многочисленные модули и веб-фронты в одном)

Как с этим зоопарком жить-то потом, джобы дублировать, обеспечивать целостность доработок?
Часто новые сущности должны делаться и на бэке и на фронте одновременно... Как потом эти разрозненные фиксы разобрать?
Со временем явно перейдем на деплои версиями, и как мы будем с этими разрозненными репозиториями работать? Как искать в них общие элементы?

Давайте будем регулярно выделять время на предварительное обсуждение таких вопросов. А то грустно от непонятных односторонних действий...

**Comment by AleksejDomash** [comment]
Активити - целостная структура, модули зависят друг от друга. Между wf проектом и порталами явной связи нет. Кроме того последовательность сборки решается дженкинсом, а не системой хранения версией.

**Comment by bvv4ik** [comment]
"Между wf проектом и порталами явной связи нет" -  ну какжеж нет?
если убрать некоторые элементы сущности с бэка - фронт поламается.
Последовательность сборки нас как раз не сильно интересует, а вот целостность версии - очень даже. И эта целостность включает в себя бэк и фронт.
