### ISSUE TITLE
Интеграция с BankID

### ISSUE THREAD

**Issue by PavelKorchagin** [e-government-ua/dniprorada#5]
кнопка представиться

**Comment by AleksejDomash** [comment]
resources to use
https://github.com/jaredhanson/oauth2orize

http://scottksmith.com/blog/2014/07/02/beer-locker-building-a-restful-api-with-node-oauth2-server/

**Comment by AleksejDomash** [comment]
прогресс 70%

**Comment by bvv4ik** [comment]
я так понимаю - это-ж готово?
