### ISSUE TITLE
Portal activiti form rendering

### ISSUE THREAD

**Issue by PavelKorchagin** [e-government-ua/dniprorada#7]
Добавить рендеринг поле дата, enum

**Comment by maxtmn** [comment]
какой формат даты делать?
что нужно от ENUM?

**Comment by PavelKorchagin** [comment]
http://activiti.org/userguide/index.html#_forms

**Comment by PavelKorchagin** [comment]
Для поля типа enum 
"type" : "enum",

рендерить select с options 

 "enumValues" : [
            {
              "id" : "normal",
              "name" : "Normal bed"
            },
            {
              "id" : "kingsize",
              "name" : "Kingsize bed"
            },
          ]

**Comment by bvv4ik** [comment]
комбобокс готов
