### ISSUE TITLE
Изменить главную страницу портала

### ISSUE THREAD

**Issue by kurbpa** [e-government-ua/dniprorada#9]
1. В шапке написать: Електронні послуги
2. Из лого убрать e-gov (оставить только лого Рады)
3. убрать пункты меню сверху
4. убрать надпись “Бізнес-процеси:”.
5. все ссылки на услуги должны быть просто в столбик, друг под другом
6. футер тоже пока убрать

**Comment by bvv4ik** [comment]
готово
